name: Run Appium Tests on PR

on:
  pull_request:
    branches:
      - main  # Trigger this workflow on pull request to 'main'

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        options: --entrypoint "/bin/bash -c 'appium'"  # Start the Appium server in a Docker container

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'   # Install Java 11 (or any version your tests need)

      - name: Install dependencies
        run: mvn install  # Run Maven to install your dependencies from pom.xml

      - name: Run Appium tests
        run: mvn test  # Run all the tests in your project

      - name: Verify test results
        if: ${{ failure() }}
        run: echo "Tests failed. PR cannot be merged."  # Display a failure message if tests fail
        continue-on-error: true
